// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	Ping(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	DeploySpecifications(ctx context.Context, opts ...grpc.CallOption) (RuntimeService_DeploySpecificationsClient, error)
	DeploySpecification(ctx context.Context, in *DeploySpecificationRequest, opts ...grpc.CallOption) (*DeploySpecificationResponse, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) Ping(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/v1.RuntimeService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) DeploySpecifications(ctx context.Context, opts ...grpc.CallOption) (RuntimeService_DeploySpecificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RuntimeService_serviceDesc.Streams[0], "/v1.RuntimeService/DeploySpecifications", opts...)
	if err != nil {
		return nil, err
	}
	x := &runtimeServiceDeploySpecificationsClient{stream}
	return x, nil
}

type RuntimeService_DeploySpecificationsClient interface {
	Send(*DeploySpecificationRequest) error
	Recv() (*DeploySpecificationResponse, error)
	grpc.ClientStream
}

type runtimeServiceDeploySpecificationsClient struct {
	grpc.ClientStream
}

func (x *runtimeServiceDeploySpecificationsClient) Send(m *DeploySpecificationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *runtimeServiceDeploySpecificationsClient) Recv() (*DeploySpecificationResponse, error) {
	m := new(DeploySpecificationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runtimeServiceClient) DeploySpecification(ctx context.Context, in *DeploySpecificationRequest, opts ...grpc.CallOption) (*DeploySpecificationResponse, error) {
	out := new(DeploySpecificationResponse)
	err := c.cc.Invoke(ctx, "/v1.RuntimeService/DeploySpecification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility
type RuntimeServiceServer interface {
	Ping(context.Context, *VersionRequest) (*VersionResponse, error)
	DeploySpecifications(RuntimeService_DeploySpecificationsServer) error
	DeploySpecification(context.Context, *DeploySpecificationRequest) (*DeploySpecificationResponse, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRuntimeServiceServer struct {
}

func (UnimplementedRuntimeServiceServer) Ping(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRuntimeServiceServer) DeploySpecifications(RuntimeService_DeploySpecificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method DeploySpecifications not implemented")
}
func (UnimplementedRuntimeServiceServer) DeploySpecification(context.Context, *DeploySpecificationRequest) (*DeploySpecificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploySpecification not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	s.RegisterService(&_RuntimeService_serviceDesc, srv)
}

func _RuntimeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RuntimeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).Ping(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_DeploySpecifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServiceServer).DeploySpecifications(&runtimeServiceDeploySpecificationsServer{stream})
}

type RuntimeService_DeploySpecificationsServer interface {
	Send(*DeploySpecificationResponse) error
	Recv() (*DeploySpecificationRequest, error)
	grpc.ServerStream
}

type runtimeServiceDeploySpecificationsServer struct {
	grpc.ServerStream
}

func (x *runtimeServiceDeploySpecificationsServer) Send(m *DeploySpecificationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *runtimeServiceDeploySpecificationsServer) Recv() (*DeploySpecificationRequest, error) {
	m := new(DeploySpecificationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RuntimeService_DeploySpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploySpecificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).DeploySpecification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RuntimeService/DeploySpecification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).DeploySpecification(ctx, req.(*DeploySpecificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RuntimeService_Ping_Handler,
		},
		{
			MethodName: "DeploySpecification",
			Handler:    _RuntimeService_DeploySpecification_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeploySpecifications",
			Handler:       _RuntimeService_DeploySpecifications_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/app.proto",
}
